on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test on node $ and $
    runs-on: $
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest] 

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js $
      uses: actions/setup-node@v1
      with:
        node-version: $

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
        
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        xcodebuild test -project Algo.xcodeproj -scheme Algo -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.6'
    - name: Run tests
      run: swift test -v
