name: Swift

on:
  push:
    branches: [ main, dev, mapView ]
  pull_request:
    branches: [ main, dev, mapView ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: swift-format-lint
      uses: Iron-Ham/swift-format-linter-action@v5
